// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/genexecuteall. DO NOT EDIT.

package dpf

import "net/http"

// ExecuteAll は Pager である Execute() を全ページ分繰り返し呼び出し、
// すべての結果(Results)を結合した *GetCommonConfigs を返す。
// 1ページあたりの取得件数(limit)は 10000（通常の一覧 API）。
// 途中でエラーが発生した場合は、それまでに取得した結果とエラーを返す。
func (r ApiGetCommonConfigListRequest) ExecuteAll() (*GetCommonConfigs, *http.Response, error) {
	const pageSize = int32(10000)
	var all *GetCommonConfigs
	var resp *http.Response
	for offset := int32(0); ; offset += pageSize {
		o := offset
		l := pageSize
		r.offset = &o
		r.limit = &l
		page, pageResp, err := r.Execute()
		resp = pageResp
		if err != nil {
			return all, resp, err
		}
		if page == nil {
			break
		}
		if all == nil {
			all = page
		} else {
			all.Results = append(all.Results, page.Results...)
		}
		if int32(len(page.Results)) < pageSize {
			break
		}
	}
	return all, resp, nil
}

// ExecuteAll は Pager である Execute() を全ページ分繰り返し呼び出し、
// すべての結果(Results)を結合した *GetContracts を返す。
// 1ページあたりの取得件数(limit)は 10000（通常の一覧 API）。
// 途中でエラーが発生した場合は、それまでに取得した結果とエラーを返す。
func (r ApiGetContractListRequest) ExecuteAll() (*GetContracts, *http.Response, error) {
	const pageSize = int32(10000)
	var all *GetContracts
	var resp *http.Response
	for offset := int32(0); ; offset += pageSize {
		o := offset
		l := pageSize
		r.offset = &o
		r.limit = &l
		page, pageResp, err := r.Execute()
		resp = pageResp
		if err != nil {
			return all, resp, err
		}
		if page == nil {
			break
		}
		if all == nil {
			all = page
		} else {
			all.Results = append(all.Results, page.Results...)
		}
		if int32(len(page.Results)) < pageSize {
			break
		}
	}
	return all, resp, nil
}

// ExecuteAll は Pager である Execute() を全ページ分繰り返し呼び出し、
// すべての結果(Results)を結合した *GetLbDomains を返す。
// 1ページあたりの取得件数(limit)は 10000（通常の一覧 API）。
// 途中でエラーが発生した場合は、それまでに取得した結果とエラーを返す。
func (r ApiGetContractsLbDomainListRequest) ExecuteAll() (*GetLbDomains, *http.Response, error) {
	const pageSize = int32(10000)
	var all *GetLbDomains
	var resp *http.Response
	for offset := int32(0); ; offset += pageSize {
		o := offset
		l := pageSize
		r.offset = &o
		r.limit = &l
		page, pageResp, err := r.Execute()
		resp = pageResp
		if err != nil {
			return all, resp, err
		}
		if page == nil {
			break
		}
		if all == nil {
			all = page
		} else {
			all.Results = append(all.Results, page.Results...)
		}
		if int32(len(page.Results)) < pageSize {
			break
		}
	}
	return all, resp, nil
}

// ExecuteAll は Pager である Execute() を全ページ分繰り返し呼び出し、
// すべての結果(Results)を結合した *GetContractsLogs を返す。
// 1ページあたりの取得件数(limit)は 100（log 系 API）。
// 途中でエラーが発生した場合は、それまでに取得した結果とエラーを返す。
func (r ApiGetContractsLogListRequest) ExecuteAll() (*GetContractsLogs, *http.Response, error) {
	const pageSize = int32(100)
	var all *GetContractsLogs
	var resp *http.Response
	for offset := int32(0); ; offset += pageSize {
		o := offset
		l := pageSize
		r.offset = &o
		r.limit = &l
		page, pageResp, err := r.Execute()
		resp = pageResp
		if err != nil {
			return all, resp, err
		}
		if page == nil {
			break
		}
		if all == nil {
			all = page
		} else {
			all.Results = append(all.Results, page.Results...)
		}
		if int32(len(page.Results)) < pageSize {
			break
		}
	}
	return all, resp, nil
}

// ExecuteAll は Pager である Execute() を全ページ分繰り返し呼び出し、
// すべての結果(Results)を結合した *GetZones を返す。
// 1ページあたりの取得件数(limit)は 10000（通常の一覧 API）。
// 途中でエラーが発生した場合は、それまでに取得した結果とエラーを返す。
func (r ApiGetContractsZoneListRequest) ExecuteAll() (*GetZones, *http.Response, error) {
	const pageSize = int32(10000)
	var all *GetZones
	var resp *http.Response
	for offset := int32(0); ; offset += pageSize {
		o := offset
		l := pageSize
		r.offset = &o
		r.limit = &l
		page, pageResp, err := r.Execute()
		resp = pageResp
		if err != nil {
			return all, resp, err
		}
		if page == nil {
			break
		}
		if all == nil {
			all = page
		} else {
			all.Results = append(all.Results, page.Results...)
		}
		if int32(len(page.Results)) < pageSize {
			break
		}
	}
	return all, resp, nil
}

// ExecuteAll は Pager である Execute() を全ページ分繰り返し呼び出し、
// すべての結果(Results)を結合した *GetDelegations を返す。
// 1ページあたりの取得件数(limit)は 10000（通常の一覧 API）。
// 途中でエラーが発生した場合は、それまでに取得した結果とエラーを返す。
func (r ApiGetDelegationListRequest) ExecuteAll() (*GetDelegations, *http.Response, error) {
	const pageSize = int32(10000)
	var all *GetDelegations
	var resp *http.Response
	for offset := int32(0); ; offset += pageSize {
		o := offset
		l := pageSize
		r.offset = &o
		r.limit = &l
		page, pageResp, err := r.Execute()
		resp = pageResp
		if err != nil {
			return all, resp, err
		}
		if page == nil {
			break
		}
		if all == nil {
			all = page
		} else {
			all.Results = append(all.Results, page.Results...)
		}
		if int32(len(page.Results)) < pageSize {
			break
		}
	}
	return all, resp, nil
}

// ExecuteAll は Pager である Execute() を全ページ分繰り返し呼び出し、
// すべての結果(Results)を結合した *GetLbDomains を返す。
// 1ページあたりの取得件数(limit)は 10000（通常の一覧 API）。
// 途中でエラーが発生した場合は、それまでに取得した結果とエラーを返す。
func (r ApiGetLbDomainListRequest) ExecuteAll() (*GetLbDomains, *http.Response, error) {
	const pageSize = int32(10000)
	var all *GetLbDomains
	var resp *http.Response
	for offset := int32(0); ; offset += pageSize {
		o := offset
		l := pageSize
		r.offset = &o
		r.limit = &l
		page, pageResp, err := r.Execute()
		resp = pageResp
		if err != nil {
			return all, resp, err
		}
		if page == nil {
			break
		}
		if all == nil {
			all = page
		} else {
			all.Results = append(all.Results, page.Results...)
		}
		if int32(len(page.Results)) < pageSize {
			break
		}
	}
	return all, resp, nil
}

// ExecuteAll は Pager である Execute() を全ページ分繰り返し呼び出し、
// すべての結果(Results)を結合した *GetLbDomainsLogs を返す。
// 1ページあたりの取得件数(limit)は 100（log 系 API）。
// 途中でエラーが発生した場合は、それまでに取得した結果とエラーを返す。
func (r ApiGetLbDomainsLogListRequest) ExecuteAll() (*GetLbDomainsLogs, *http.Response, error) {
	const pageSize = int32(100)
	var all *GetLbDomainsLogs
	var resp *http.Response
	for offset := int32(0); ; offset += pageSize {
		o := offset
		l := pageSize
		r.offset = &o
		r.limit = &l
		page, pageResp, err := r.Execute()
		resp = pageResp
		if err != nil {
			return all, resp, err
		}
		if page == nil {
			break
		}
		if all == nil {
			all = page
		} else {
			all.Results = append(all.Results, page.Results...)
		}
		if int32(len(page.Results)) < pageSize {
			break
		}
	}
	return all, resp, nil
}

// ExecuteAll は Pager である Execute() を全ページ分繰り返し呼び出し、
// すべての結果(Results)を結合した *GetRecords を返す。
// 1ページあたりの取得件数(limit)は 10000（通常の一覧 API）。
// 途中でエラーが発生した場合は、それまでに取得した結果とエラーを返す。
func (r ApiGetRecordCurrentsRequest) ExecuteAll() (*GetRecords, *http.Response, error) {
	const pageSize = int32(10000)
	var all *GetRecords
	var resp *http.Response
	for offset := int32(0); ; offset += pageSize {
		o := offset
		l := pageSize
		r.offset = &o
		r.limit = &l
		page, pageResp, err := r.Execute()
		resp = pageResp
		if err != nil {
			return all, resp, err
		}
		if page == nil {
			break
		}
		if all == nil {
			all = page
		} else {
			all.Results = append(all.Results, page.Results...)
		}
		if int32(len(page.Results)) < pageSize {
			break
		}
	}
	return all, resp, nil
}

// ExecuteAll は Pager である Execute() を全ページ分繰り返し呼び出し、
// すべての結果(Results)を結合した *GetRecordsDiffs を返す。
// 1ページあたりの取得件数(limit)は 10000（通常の一覧 API）。
// 途中でエラーが発生した場合は、それまでに取得した結果とエラーを返す。
func (r ApiGetRecordDiffsRequest) ExecuteAll() (*GetRecordsDiffs, *http.Response, error) {
	const pageSize = int32(10000)
	var all *GetRecordsDiffs
	var resp *http.Response
	for offset := int32(0); ; offset += pageSize {
		o := offset
		l := pageSize
		r.offset = &o
		r.limit = &l
		page, pageResp, err := r.Execute()
		resp = pageResp
		if err != nil {
			return all, resp, err
		}
		if page == nil {
			break
		}
		if all == nil {
			all = page
		} else {
			all.Results = append(all.Results, page.Results...)
		}
		if int32(len(page.Results)) < pageSize {
			break
		}
	}
	return all, resp, nil
}

// ExecuteAll は Pager である Execute() を全ページ分繰り返し呼び出し、
// すべての結果(Results)を結合した *GetRecords を返す。
// 1ページあたりの取得件数(limit)は 10000（通常の一覧 API）。
// 途中でエラーが発生した場合は、それまでに取得した結果とエラーを返す。
func (r ApiGetRecordListRequest) ExecuteAll() (*GetRecords, *http.Response, error) {
	const pageSize = int32(10000)
	var all *GetRecords
	var resp *http.Response
	for offset := int32(0); ; offset += pageSize {
		o := offset
		l := pageSize
		r.offset = &o
		r.limit = &l
		page, pageResp, err := r.Execute()
		resp = pageResp
		if err != nil {
			return all, resp, err
		}
		if page == nil {
			break
		}
		if all == nil {
			all = page
		} else {
			all.Results = append(all.Results, page.Results...)
		}
		if int32(len(page.Results)) < pageSize {
			break
		}
	}
	return all, resp, nil
}

// ExecuteAll は Pager である Execute() を全ページ分繰り返し呼び出し、
// すべての結果(Results)を結合した *GetTsigsCommonConfigs を返す。
// 1ページあたりの取得件数(limit)は 10000（通常の一覧 API）。
// 途中でエラーが発生した場合は、それまでに取得した結果とエラーを返す。
func (r ApiGetTsigCommonConfigsRequest) ExecuteAll() (*GetTsigsCommonConfigs, *http.Response, error) {
	const pageSize = int32(10000)
	var all *GetTsigsCommonConfigs
	var resp *http.Response
	for offset := int32(0); ; offset += pageSize {
		o := offset
		l := pageSize
		r.offset = &o
		r.limit = &l
		page, pageResp, err := r.Execute()
		resp = pageResp
		if err != nil {
			return all, resp, err
		}
		if page == nil {
			break
		}
		if all == nil {
			all = page
		} else {
			all.Results = append(all.Results, page.Results...)
		}
		if int32(len(page.Results)) < pageSize {
			break
		}
	}
	return all, resp, nil
}

// ExecuteAll は Pager である Execute() を全ページ分繰り返し呼び出し、
// すべての結果(Results)を結合した *GetTsigs を返す。
// 1ページあたりの取得件数(limit)は 10000（通常の一覧 API）。
// 途中でエラーが発生した場合は、それまでに取得した結果とエラーを返す。
func (r ApiGetTsigListRequest) ExecuteAll() (*GetTsigs, *http.Response, error) {
	const pageSize = int32(10000)
	var all *GetTsigs
	var resp *http.Response
	for offset := int32(0); ; offset += pageSize {
		o := offset
		l := pageSize
		r.offset = &o
		r.limit = &l
		page, pageResp, err := r.Execute()
		resp = pageResp
		if err != nil {
			return all, resp, err
		}
		if page == nil {
			break
		}
		if all == nil {
			all = page
		} else {
			all.Results = append(all.Results, page.Results...)
		}
		if int32(len(page.Results)) < pageSize {
			break
		}
	}
	return all, resp, nil
}

// ExecuteAll は Pager である Execute() を全ページ分繰り返し呼び出し、
// すべての結果(Results)を結合した *GetZoneHistories を返す。
// 1ページあたりの取得件数(limit)は 10000（通常の一覧 API）。
// 途中でエラーが発生した場合は、それまでに取得した結果とエラーを返す。
func (r ApiGetZoneHistoryListRequest) ExecuteAll() (*GetZoneHistories, *http.Response, error) {
	const pageSize = int32(10000)
	var all *GetZoneHistories
	var resp *http.Response
	for offset := int32(0); ; offset += pageSize {
		o := offset
		l := pageSize
		r.offset = &o
		r.limit = &l
		page, pageResp, err := r.Execute()
		resp = pageResp
		if err != nil {
			return all, resp, err
		}
		if page == nil {
			break
		}
		if all == nil {
			all = page
		} else {
			all.Results = append(all.Results, page.Results...)
		}
		if int32(len(page.Results)) < pageSize {
			break
		}
	}
	return all, resp, nil
}

// ExecuteAll は Pager である Execute() を全ページ分繰り返し呼び出し、
// すべての結果(Results)を結合した *GetZones を返す。
// 1ページあたりの取得件数(limit)は 10000（通常の一覧 API）。
// 途中でエラーが発生した場合は、それまでに取得した結果とエラーを返す。
func (r ApiGetZoneListRequest) ExecuteAll() (*GetZones, *http.Response, error) {
	const pageSize = int32(10000)
	var all *GetZones
	var resp *http.Response
	for offset := int32(0); ; offset += pageSize {
		o := offset
		l := pageSize
		r.offset = &o
		r.limit = &l
		page, pageResp, err := r.Execute()
		resp = pageResp
		if err != nil {
			return all, resp, err
		}
		if page == nil {
			break
		}
		if all == nil {
			all = page
		} else {
			all.Results = append(all.Results, page.Results...)
		}
		if int32(len(page.Results)) < pageSize {
			break
		}
	}
	return all, resp, nil
}

// ExecuteAll は Pager である Execute() を全ページ分繰り返し呼び出し、
// すべての結果(Results)を結合した *GetZonesLogs を返す。
// 1ページあたりの取得件数(limit)は 100（log 系 API）。
// 途中でエラーが発生した場合は、それまでに取得した結果とエラーを返す。
func (r ApiGetZonesLogListRequest) ExecuteAll() (*GetZonesLogs, *http.Response, error) {
	const pageSize = int32(100)
	var all *GetZonesLogs
	var resp *http.Response
	for offset := int32(0); ; offset += pageSize {
		o := offset
		l := pageSize
		r.offset = &o
		r.limit = &l
		page, pageResp, err := r.Execute()
		resp = pageResp
		if err != nil {
			return all, resp, err
		}
		if page == nil {
			break
		}
		if all == nil {
			all = page
		} else {
			all.Results = append(all.Results, page.Results...)
		}
		if int32(len(page.Results)) < pageSize {
			break
		}
	}
	return all, resp, nil
}
